server:
  port: 8082  #服务端口号

spring:
  application:
    name: provider #服务名称--调用的时候根据名称来调用该服务的方法
eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/
  instance:
    instance-id: mircorsevicecloud-provider-8082 #自定义注册名称
    prefer-ip-address: true #访问显示ip地址
info:
  app.name: provider
  company.name: test
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}